// function func(fun,a,b){
//     return fun(a,b)
// }

// function add(a,b){
//     return a+b;
// }

// let result = func(add,1,2);

// console.log(result);


// .................higher order functions............

// function fun(){
//     return function(){
//         console.log("Hello!");
//     }
// }

// let res = fun();
// console.log(typeof res);
// console.log(res);

// res();





// .............for each method...............               

names = ["arun",'ram','arjun'];

names.forEach((player)=>console.log(player));

arr = [1,2,3,4,5];
The `// filter...........` comment is likely indicating that the code snippet is about to demonstrate the usage of the `filter` method in JavaScript. However, the code snippet provided does not actually contain any implementation of the `filter` method.

// map...........
cube_arr = arr.map(i => i**3);

console.log(cube_arr)
console.log(arr);

// ..............filter...........